---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inference-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inference-operator-manager-role
subjects:
- kind: ServiceAccount
  name: inference-operator-controller-manager
  namespace: inference-system
